### ISSUE TITLE
Questions on caption and activityViewController

### ISSUE THREAD

**Issue by s2imon** [attilaroy/share-instagram-swift#1]
Hi there, looks neat. I'm looking for something like this, however I was wondering what the deal was with the caption not showing and activityViewController opening instead of the Instagram app opening directly (running the example code on the phone). Are these limitations of iOS/the sharing setup or am I missing something? Thanks a bunch!

**Comment by sashabaranov** [comment]
Same here, method covered in this example and in [SO](https://stackoverflow.com/questions/31337490/how-to-share-image-in-instagramswift) does invoke activity view controller now. Tested on iOS 12.2 and whatever latest version of Instagram app is out today.

**Comment by sashabaranov** [comment]
@attilaroy can you confirm this?

**Comment by attilaroy** [comment]
@s2imon @sashabaranov It seems like Instagram has removed the caption option.

For your reference
https://stackoverflow.com/questions/31915122/instagram-instagramcaption-not-working
https://stackoverflow.com/questions/31012861/missing-instagram-caption-in-ios-9-app

**Comment by danya61** [comment]
> @attilaroy can you confirm this?

did you find another solution?
